spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcmdata?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
    
  jpa:
    database: MYSQL
    show-sql: true
    format-sql: true
    use-sql-comments: true
    hibernate:
      ddl-auto: update
      
  mvc:
    view:
      prefix: /
      suffix: html
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
      
  security:
    user:
      name: user
      password: password
      role: USER

      
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  